### ISSUE TITLE
duplication of some root RDF properties

### ISSUE THREAD

**Issue by ericprud** [w3c/hcls-fhir-rdf#114]
**Turtle filename**
[codesystem-contact-point-use](https://build.fhir.org/codesystem-contact-point-use.ttl.html)

**FHIR Resource**
[https://build.fhir.org/codesystem.html#CodeSystem](https://build.fhir.org/codesystem.html#CodeSystem)

**ShEx shape**
[`@<CodeSystem>~fhir:identifier`](https://build.fhir.org/codesystem.shex.html)

**Description**
What the Turtle should be. Can express as diff à la:
``` diff
-  fhir:identifier ( [
-     fhir:system [ fhir:v "urn:ietf:rfc:3986" ] ;
-     fhir:value [ fhir:v "urn:oid:2.16.840.1.113883.4.642.1.74" ]
-  ] [
-     fhir:system [ fhir:v "urn:ietf:rfc:3986" ] ;
-     fhir:value [ fhir:v "urn:oid:2.16.840.1.113883.4.642.1.74" ]
-  ] ) ;
-  fhir:version [ fhir:v "6.0.0-cibuild"], [ fhir:v "6.0.0-cibuild"] ;
+  fhir:identifier ( [
+     fhir:system [ fhir:v "urn:ietf:rfc:3986" ] ;
+     fhir:value [ fhir:v "urn:oid:2.16.840.1.113883.4.642.1.74" ]
+  ] ) ;
+  fhir:version [ fhir:v "6.0.0-cibuild"] ;
```

**Comment by dbooth-boston** [comment]
Confirmed fixed in https://github.com/HL7/kindling/pull/148

**Comment by ericprud** [comment]
can you point to evidence and close the issue?

**Comment by dbooth-boston** [comment]
Closing as fixed in https://github.com/w3c/hcls-fhir-rdf/issues/117
