### ISSUE TITLE
missing Narrative.div

### ISSUE THREAD

**Issue by ericprud** [w3c/hcls-fhir-rdf#115]
**Turtle filename**
[codesystem-contact-point-use](https://build.fhir.org/codesystem-contact-point-use.ttl.html)
contrast with [JSON](https://build.fhir.org/codesystem-contact-point-use.json.html)

**FHIR Resource**
[https://build.fhir.org/narrative#ab](https://build.fhir.org/narrative#ab)

**ShEx shape**
[`@<Narrative>~fhir:div`](https://build.fhir.org/narrative.shex.html)

**Description**
``` diff
   fhir:text [
-     fhir:status [ fhir:v "generated" ]
+     fhir:status [ fhir:v "generated" ];
+     fhir:div "<div xmlns=\"http://www.w3.org/1999/xhtml\">…</div>"
   ] ;
```

**Comment by dbooth-boston** [comment]
Confirmed fixed in https://github.com/HL7/kindling/pull/148

**Comment by ericprud** [comment]
Can you drop a link to evidence and close this?

**Comment by dbooth-boston** [comment]
Closing, as fixed in https://github.com/HL7/kindling/pull/148
