### ISSUE TITLE
missing datatype for FHIR primitive types

### ISSUE THREAD

**Issue by ericprud** [w3c/hcls-fhir-rdf#117]
**Turtle filename**
[codesystem-contact-point-use](https://build.fhir.org/codesystem-contact-point-use.ttl.html)

**FHIR Resource**
[http://build.fhir.org/datatypes.html#code](http://build.fhir.org/datatypes.html#code)
[http://build.fhir.org/datatypes.html#date](http://build.fhir.org/datatypes.html#date)
[http://build.fhir.org/datatypes.html#instant](http://build.fhir.org/datatypes.html#instant)
[http://build.fhir.org/datatypes.html#uri](http://build.fhir.org/datatypes.html#uri)

**ShEx shape**
[`@<code>~fhir:v`](https://github.com/fhircat/ShExValidation/blob/cc66c8094916908d2acabc443e5f7a6ae63fb606/fhir_rdf_validation/ShExSchemas/R5Plus/code.shex#L15)
[`@<date>~fhir:v`](https://github.com/fhircat/ShExValidation/blob/cc66c8094916908d2acabc443e5f7a6ae63fb606/fhir_rdf_validation/ShExSchemas/R5Plus/date.shex#L15)
[`@<instant>~fhir:v`](https://github.com/fhircat/ShExValidation/blob/cc66c8094916908d2acabc443e5f7a6ae63fb606/fhir_rdf_validation/ShExSchemas/R5Plus/instant.shex#L15)
[`@<uri>~fhir:v`](https://github.com/fhircat/ShExValidation/blob/cc66c8094916908d2acabc443e5f7a6ae63fb606/fhir_rdf_validation/ShExSchemas/R5Plus/uri.shex#L15)

**Description**
What the Turtle should be. Can express as diff à la:
``` diff
   fhir:meta [
-     fhir:lastUpdated [ fhir:v "2023-05-26T00:17:51.868+00:00" ]
+     fhir:lastUpdated [ fhir:v "2023-05-26T00:17:51.868+00:00"^^xsd:dateTime ]
   ] ;
   …
-  fhir:url [ fhir:v "http://hl7.org/fhir/contact-point-use"] ;
+  fhir:url [ fhir:v "http://hl7.org/fhir/contact-point-use"^^xsd:anyURI] ;
   …
   fhir:text [
-     fhir:status [ fhir:v "generated" ]
+     fhir:status [ fhir:v "generated"^^xsd:token ]
   ] ;
   …
-  fhir:date [ fhir:v "2023-05-26T00:17:51+00:00"] ;
+  fhir:date [ fhir:v "2023-05-26T00:17:51+00:00"^^xsd:dateTime] ;
   
```

**Comment by dbooth-boston** [comment]
This is partially fixed by https://github.com/HL7/kindling/pull/148 .  These parts are fixed:
```
+     fhir:lastUpdated [ fhir:v "2023-05-26T00:17:51.868+00:00"^^xsd:dateTime ]
+  fhir:url [ fhir:v "http://hl7.org/fhir/contact-point-use"^^xsd:anyURI] ;
+  fhir:date [ fhir:v "2023-05-26T00:17:51+00:00"^^xsd:dateTime] ;
```

But this one still needs the xsd:token type:
```
-     fhir:status [ fhir:v "generated" ]
+     fhir:status [ fhir:v "generated"^^xsd:token ]
```

**Comment by balhoff** [comment]
@dbooth-boston you can assign me.

**Comment by dbooth-boston** [comment]
Closing as fixed in https://github.com/w3c/hcls-fhir-rdf/issues/117
