### ISSUE TITLE
Add clarification to rdf.html page about using OWL

### ISSUE THREAD

**Issue by dbooth-boston** [w3c/hcls-fhir-rdf#128]
Add to explanation to rdf.html page: "1. apply the RDF list SPARQL update transformation to your data file. 2. Merge the ontology into your data file. 3. Open in Protege. "  Per Jim: But then it will still be very hard to navigate since all individuals are anonymous. Maybe we should also provide a SPARQL update to swap in skolem IRIs for all individuals

**Comment by dbooth-boston** [comment]
I think the [SPARQL script page](https://github.com/w3c/hcls-fhir-rdf/blob/gh-pages/scripts/owl-safe-lists/README.md) is actually a better place for this guidance.  @balhoff Does that updated explanation look okay to you?

**Comment by balhoff** [comment]
@dbooth-boston it sounds good to me.

**Comment by dbooth-boston** [comment]
Closing as done.
