### ISSUE TITLE
Should we define uri template guidance for vocabularies (coding system + code)?

### ISSUE THREAD

**Issue by dbooth-boston** [w3c/hcls-fhir-rdf#13]
Imported from W3C issues list: https://www.w3.org/2014/HCLS/track/issues/11
https://www.w3.org/2015/06/09-hcls-minutes.html#item05

**Comment by tmallia** [comment]
We could recommend to terminologies that they adopt a URI structure. SNOMED has already defined one and it could be adopted by others but it is up to the terminology to define their URIs.
That said it would be useful to have a standard across terminologies.

**Comment by dbooth-boston** [comment]
AGREED: Too difficult to get all terminology publishers to use the same template, and no benefit unless they all do.

See http://www.w3.org/2016/11/22-hcls-irc#T16-50-12
