### ISSUE TITLE
w5 ontology version IRI is stored as a string

### ISSUE THREAD

**Issue by balhoff** [w3c/hcls-fhir-rdf#131]
In the `http://hl7.org/fhir/R5/w5.ttl` ontology, which can be downloaded from https://www.hl7.org/fhir/downloads.html, the version IRI is stored as a string rather than an IRI:

```turtle
fhir:w5.ttl owl:versionIRI "http://hl7.org/fhir/R5/w5.ttl" .
```

Should be:

```turtle
fhir:w5.ttl owl:versionIRI <http://hl7.org/fhir/R5/w5.ttl> .
```

From #48.

**Comment by dbooth-boston** [comment]
Jim: Still waiting to be merged.

**Comment by dbooth-boston** [comment]
Merged: https://github.com/HL7/kindling/pull/137
