### ISSUE TITLE
Update Unit Tests for RDF generation

### ISSUE THREAD

**Issue by tmprd** [w3c/hcls-fhir-rdf#136]
Unit tests for R5 turtle generation should be setup and documented. Tests for example instances would be especially helpful, in order to quickly resolve current issues with example instances. Those tests should also document clearly where the test example files are.

# R5+
* [TurtleParser.java](https://github.com/hapifhir/org.hl7.fhir.core/blob/master/org.hl7.fhir.r5/src/main/java/org/hl7/fhir/r5/elementmodel/TurtleParser.java) is used for generating R5 turtle, so it should be used in unit tests.
* Current tests go [here](https://github.com/hapifhir/org.hl7.fhir.core/tree/master/org.hl7.fhir.r5/src/test/java/org/hl7/fhir/r5/test)
  * [ShexGeneratorTests.java](https://github.com/hapifhir/org.hl7.fhir.core/blob/c717f898effc64511646fcc80071cc7b06876bd0/org.hl7.fhir.r5/src/test/java/org/hl7/fhir/r5/test/ShexGeneratorTests.java) currently provide tests for some StructureDefinitions
  * [Some](https://github.com/hapifhir/org.hl7.fhir.core/blob/c717f898effc64511646fcc80071cc7b06876bd0/org.hl7.fhir.r5/src/test/java/org/hl7/fhir/r5/test/ValidationTestConvertor.java#L34) other existing tests mention turtle

# Documentation
Documentation should be added to this repo, as in #135 
(See https://github.com/tmprd/hcls-fhir-rdf/tree/generation-documentation#rdf--shex-generation)

# Versions before R5
Previous FHIR versions use a different RDF parser & generator, and had some tests setup. 
* [R4 turtle generator](https://github.com/hapifhir/org.hl7.fhir.core/blob/master/org.hl7.fhir.r4/src/main/java/org/hl7/fhir/r4/formats/RdfParser.java)
* [R4 Tests](https://github.com/hapifhir/org.hl7.fhir.core/tree/master/org.hl7.fhir.r4/src/test/java/org/hl7/fhir/r4/test)
  * [TurtleTests.java](https://github.com/hapifhir/org.hl7.fhir.core/blob/master/org.hl7.fhir.r4/src/test/java/org/hl7/fhir/r4/test/TurtleTests.java) provides a good set of unit tests for parsing R4 Turtle, but I was unable to find something like this for R5
  * The turtle resources tested here are in [test resources](https://github.com/hapifhir/org.hl7.fhir.core/tree/master/org.hl7.fhir.r4/src/test/resources)

* [DSTU3 Tests](https://github.com/hapifhir/org.hl7.fhir.core/tree/master/org.hl7.fhir.dstu3/src/test/java/org/hl7/fhir/dstu3/test)

# HAPI FHIR
* [Parser here](https://github.com/hapifhir/hapi-fhir/blob/52f3ef599271e47e3856151104649711d505c4aa/hapi-fhir-base/src/main/java/ca/uhn/fhir/parser/RDFParser.java)
* [Tests here](https://github.com/hapifhir/hapi-fhir/blob/939a57960dd021bb7cac7ca958b97c245803af87/hapi-fhir-structures-r4/src/test/java/ca/uhn/fhir/parser/RDFParserTest.java)

**Comment by ericprud** [comment]
I created [a codespace](https://bug-free-broccoli-xg574wjvgf69q9.github.dev/?autoStart=false) for this PR.
(Still not sure what that means).

**Comment by dbooth-boston** [comment]
@ericprud that codespace link is 404.  What still needs to be done to resolve this issue?  Does the merge of @tmprd 's PR resolve it?

@tmprd Did the merge of your PR resolve this issue?

**Comment by tmprd** [comment]
Yes the tests are in! For now they're disabled (with a simple annotation) from running automatically in the testing pipeline, but they can be run manually to more quickly test changes during development.
