### ISSUE TITLE
DICOM RDF Serialization Proposals

### ISSUE THREAD

**Issue by ericprud** [w3c/hcls-fhir-rdf#147]
This comment will be maintained to include serialization proposals gathered from other issues. I'll use a thumbs-up to indicate that I think I've rolled addressed the comment. It's your discretion whether to preserve or remove addressed comments.

### Option 5 expanded with type hierarchy for null flavors
From: [#141 5 expanded](141#user-content-5-expanded)
``` turtle
PREFIX dinull: <https://dicom.nema.org/MEDICAL/Dicom/current/output/chtml/part20/sect_5.3.2.html>
dinull:UNK rdfs:label "Unknown. A proper value is applicable, but is not known." .
dinull:ASKU rdfs:label "Asked, but not known. Information was sought, but not found (e.g., the patient was asked but did not know)." ;
  rdfs:subClassOf dinull:UNK .

<>
	dcm:00080008 [ dcm:vr "CS"; dcm:Value ( "DERIVED" "PRIMARY" [ a dcm:UNK ] "SINGLE A" )] ;
	dcm:00012345 [ dcm:vr "CS"; dcm:Value ( 1 2 [ a dcm:UNK ] 4 [ a dcm:ASKU ] 6 )] ;
	dcm:00080030 [ dcm:vr "TM"; dcm:Value ( "131047" )] .
```

### Option 10 ( dcm:null bnode, XSD data types, VR types moved to ontology/SHEX/SHACL, moving Lists up to their properties)
From: [#141 10](141#user-content-10)

``` Turtle
<>
	dcm:00080008 ( "DERIVED" "PRIMARY"  [ a dcm:null ] "SINGLE A" ) ;
	dcm:00080016 ( "1.2.840.10008.5.1.4.1.1.12.1") ;
	dcm:00080018 ( "1.3.12.2.1107.5.4.3.11540117440512.19970422.140030.6" ) ;
	dcm:00080020 ( "19970422"^^xsd:date ) ;
	dcm:00080030 ( "131047"^^xsd:time ) ;
```

**Comment by ebremer** [comment]
@ericprud I think we're down to Option 10.  The dcm:UNK and dcm:ASKU were no longer necessary as they aren't part of DICOM bit a report format as @grittner-sohard pointed out.  So we only have dcm:null.

**Comment by ericprud** [comment]
> @ericprud I think we're down to Option 10. The dcm:UNK and dcm:ASKU were no longer necessary as they aren't part of DICOM bit a report format as @grittner-sohard pointed out. So we only have dcm:null.

resolved? you can delete if so.

**Comment by dbooth-boston** [comment]
Closing, Superseded by https://github.com/w3c/hcls-fhir-rdf/issues/148
