### ISSUE TITLE
Handling malformed DICOM files

### ISSUE THREAD

**Issue by ebremer** [w3c/hcls-fhir-rdf#152]
I too often come across DICOM files which do not comply with the DICOM specification.  For example, the string "Uptake" I found in a VR type IS field which should be an integer string.  How should we handle failures like this?   Store as a string in RDF and add a warning tag or fail hard?

**Comment by dbooth-boston** [comment]
Per discussion in meeting on 17-Oct-2024, closing as out of scope.
