### ISSUE TITLE
Should fhir:reference.reference->value be a string or an RDF URI node?

### ISSUE THREAD

**Issue by dbooth-boston** [w3c/hcls-fhir-rdf#16]
Imported from W3C issues list: https://www.w3.org/2014/HCLS/track/issues/16
https://www.w3.org/2015/12/01-hcls-minutes.html#item04

**Comment by mvdzel** [comment]
Is that even possible. The current root subject is a blank node.

**Comment by tmallia** [comment]
The subject can be a blank node the object cannot. I believe that there would be difficulty in creating an inverse which would have an object as a blank node. The only object property that can point to the blank node is the enclosing object property e.g. AllergyIntolerance.patient

**Comment by dbooth-boston** [comment]
Discussed ending at: http://www.w3.org/2016/04/05-hcls-irc#T22-09-24

Proposal: 
[[
lloyd: May want an additional property that is the full URI of the reference.  Take the ref and if it's relative make it absolute.  
dbooth: i.e., leave the relative URI but also have an absolute URI.
... Sounds reasonable, but want to seen an example.
]]

**Comment by mvdzel** [comment]
Example:

```
fhir:DiagnosticOrder.supportingInformationReference [fhir:index "0" ; 
      fhir:reference <http://localhost/fhir/DiagnosticOrder/example#fasting> ; 
      fhir:Reference.reference [fhir:value "#fasting"]];
```

**Comment by dbooth-boston** [comment]
Resolved.  See http://www.w3.org/2017/02/07-hcls-irc#T16-58-33
