### ISSUE TITLE
Revisiting fhir:ConceptBase and fhir:CodingBase

### ISSUE THREAD

**Issue by dbooth-boston** [w3c/hcls-fhir-rdf#21]
Should we stick with our current handling of fhir:Code, fhir:Coding and fhir:CodeableConcept, using fhir:ConceptBase and fhir:CodingBase?  I've been finding that the lack of direct correspondence between the FHIR RDF and the FHIR XML and JSON is a significant barrier.  It is making it hard to explain this part of the FHIR RDF.  

One of the good things about FHIR in general is that there is such a straightforward correspondence between the XML and JSON representations, and that really helps in making them understandable.  I think the motivation behind modeling these things using a common fhir:ConceptBase and fhir:CodingBase is to make them easier to query. But I think it is actually ending up making things harder by modeling things differently in the RDF than in the XML and JSON.  And it would make it much harder for anyone not specifically familiar with the FHIR RDF to query FHIR using SPARQL.

I'm thinking that it may be better to pull the fhir:ConceptBase and fhir:CodingBase idea out of the FHIR RDF representation, and potentially suggest it as a model that people can use internally if they wish, when they are working with their RDF.   We could even provide SPARQL rules that would translate from regular FHIR RDF to RDF that uses fhir:ConceptBase and fhir:CodingBase.

**Comment by tmallia** [comment]
I have changed the RDF/OWL back to the original CodeableConcept and tested it. It means that the elements with just fhir:code need to be treated differently from those with fhir:Coding or fhir:CodeableConcept but that difference can be handled in the FHIR internal bridging Ontology.

**Comment by dbooth-boston** [comment]
Tony has shown this this works, so I am closing the issue.
