### ISSUE TITLE
download_fhir_spec striptext option

### ISSUE THREAD

**Issue by hsolbrig** [w3c/hcls-fhir-rdf#24]
The striptext option doesn't appear to catch everything.  Use medication.profile.json from the March 30 2016 spec as an example

**Comment by dbooth-boston** [comment]
RESOLVED: Include caveat about mod exts saying that you cannot safely reason in the presence of them.
<dbooth> rrsagent, where am i?
<RRSAgent> See http://www.w3.org/2016/04/05-hcls-irc#T21-37-49

**Comment by hsolbrig** [comment]
Fixed the download_fhir_spec script to do this correctly.
