### ISSUE TITLE
What URI (if any) must be used for the root node (or target node) in a FHIR RDF document?

### ISSUE THREAD

**Issue by dbooth-boston** [w3c/hcls-fhir-rdf#3]
When/how should a URI (if any) for the root node be created/discovered?  Example: The URI for the patient, in a FHIR RDF patient record.  Should the  fhir:Reference.link be included in a transferred document?

Considerations:
 * Protege wants a URI -- not a blank node
 * The resource URI is external to the FHIR XML document.  How can it be known or made internal to the corresponding FHIR RDF?
 * The resource may not always have a stable URI, such as in a bundle
 * Important not to [squat](https://www.w3.org/wiki/UriSpaceSquatting) on others' URI spaces.

See discussion at https://www.w3.org/2016/02/02-hcls-minutes.html#item06

**Comment by tmallia** [comment]
Inside a Bundle there is a fullURI (mandatory for each contained resource).
The Absolute URL for the resource. This must be provided for all resources. The fullUrl SHALL not disagree with the id in the resource. The fullUrl is a version independent reference to the resource.

**Comment by tmallia** [comment]
•The resource URI is external to the FHIR XML document. How can it be known or made internal to the corresponding FHIR RDF?
The resource URI must be present in the Reference. The problem is that the Resource URI is hidden somewhere in the header in a simple Get response.

**Comment by mvdzel** [comment]
This is relates to the reference.reference issue, right?
Add the URI as uri or as literal.

**Comment by dbooth-boston** [comment]
Michael, the question is what should the node in RDF be called, which corresponds to the root node in FHIR XML or FHIR JSON instance data.

Grahame points out that FHIR resources can be anonymous: https://lists.w3.org/Archives/Public/public-semweb-lifesci/2016Mar/0010.html

**Comment by dbooth-boston** [comment]
http://www.w3.org/2016/04/05-hcls-irc#T15-40-16
