### ISSUE TITLE
How to handle ElementDefinition.type.aggregation

### ISSUE THREAD

**Issue by dbooth-boston** [w3c/hcls-fhir-rdf#32]
https://www.w3.org/2016/05/31-hcls-minutes.html#item03

There are several elements on that page that need to be resolved.  Harold will try to resolve the obvious ones.

**Comment by dbooth-boston** [comment]
This issue now refers only to the problem of how to handle ElementDefinition.type.aggregation .  (Others have been split out into separate issues.)

**Comment by hsolbrig** [comment]
See issue #91 for continuing discussion
