### ISSUE TITLE
Typing issues on value set references

### ISSUE THREAD

**Issue by hsolbrig** [w3c/hcls-fhir-rdf#36]
The [conceptmap-103 example](http://hl7-fhir.github.io/conceptmap-103.ttl.html) contains:

```
 fhir:ConceptMap.sourceReference [
     fhir:link <http://snomed.info/sct>;
     fhir:Reference.reference [ fhir:value "http://snomed.info/sct" ]
  ];
 fhir:ConceptMap.targetReference [
     fhir:link <http://hl7.org/fhir/sid/icd-10-us>;
     fhir:Reference.reference [ fhir:value "http://hl7.org/fhir/sid/icd-10-us" ]
  ];
   ...
  <http://hl7.org/fhir/sid/icd-10-us> a fhir:sid .
```

There is no way to determine whether a ValueSetReference actually references a value set.  This is exacerbated by the definition of sourceReference and targetReference:

```
(                                       # Identifies the source of the 
                                        # concepts which are being mapped 
        fhir:ConceptMap.sourceUri @<uri>  |
        fhir:ConceptMap.sourceReference @<ValueSetReference>  |
        fhir:ConceptMap.sourceReference @<StructureDefinitionReference> 
    );
    (                                       # Provides context to the mappings
        fhir:ConceptMap.targetUri @<uri>  |
        fhir:ConceptMap.targetReference @<ValueSetReference>  |
        fhir:ConceptMap.targetReference @<StructureDefinitionReference> 
    );
```

Where we can't tell from the RDF whether it is _supposed_ to reference a ValueSet or a StructureDefinition.

**Suggestion:**

ValueSetReferences might use different predicates: 

```
fhir:ConceptMap.targetValuSetReference
```

(This would be a breaking change, but it value set references are so different from other FHIR references that it seems that machinery might want to understand the difference up front)

**Comment by dbooth-boston** [comment]
Discussed further: http://www.w3.org/2017/02/07-hcls-irc#T16-50-57

**Comment by dbooth-boston** [comment]
Harold: THis issue requires working with FHIR community, on an enhancement to the FHIR spec.

**Comment by dbooth-boston** [comment]
https://www.w3.org/2018/09/25-hcls-irc#T15-08-08

**Comment by hsolbrig** [comment]
This may be solved by the fact that reference now has a type field, although the type has to be populated

**Comment by dbooth-boston** [comment]
Addressed by fhir:link
