### ISSUE TITLE
The type of non-fhir conformant URI's cannot be determined unless they can be de-referenced:

### ISSUE THREAD

**Issue by hsolbrig** [w3c/hcls-fhir-rdf#37]
The following EligibilityResponse example:

``` turtle
fhir:EligibilityResponse.requestReference [
     fhir:link <http://www.BenefitsInc.com/fhir/eligibility/225476332402>;
     fhir:Reference.reference [ fhir:value "http://www.BenefitsInc.com/fhir/eligibility/225476332402" ]
```

Is entirely legitimate, but it is not possible to determine the intended type of the reference unless it can be de-referenced.

**Comment by dbooth-boston** [comment]
Usually you can parse the type out of the URI string, but that is not guaranteed.   

Discussed here:
https://www.w3.org/2016/09/06-hcls-minutes.html
And then with grahame here:
http://wiki.hl7.org/index.php?title=ITS_RDF_Concall_Minutes_20160906

**Comment by dbooth-boston** [comment]
Closing with this action:

ACTION: Eric to add guidance to the FHIR RDF spec doc (at W3C) that if someone erroneously creates a ref URI that parses as though it indicates the type, but does not match the type, then validation may be wrong
