### ISSUE TITLE
What URI to use in FHIR owl:Ontology declaration

### ISSUE THREAD

**Issue by dbooth-boston** [w3c/hcls-fhir-rdf#38]
https://www.w3.org/2017/01/31-hcls-minutes.html
Harold: "ont name had to be different from the subject name. protege doesn't like something being both a person and an ontology."

**Comment by dbooth-boston** [comment]
https://www.w3.org/2017/02/07-hcls-minutes.html#item05
"harold: still pending. waiting on the imports sequence resolution."

**Comment by dbooth-boston** [comment]
Waiting for Eric to discuss protege import sequence issues with Stanford crew in March 2017.

**Comment by hsolbrig** [comment]
We need to double-check the URI's that are being generated today.  This does link to a related question (check whether there is an issue for it) as to how we represent FHIR version identifiers (STU3, R4, R5 + R5 incremantal) in the OWL headers

**Comment by dbooth-boston** [comment]
Closed.  Overtaken by events.
