### ISSUE TITLE
How to handle constraints in FHIR RDF

### ISSUE THREAD

**Issue by dbooth-boston** [w3c/hcls-fhir-rdf#39]

**Comment by ericprud** [comment]
What sort of constraints is this issue meant to address?

**Comment by hsolbrig** [comment]
The FHIR constraint language -- FHIRPath entries. The task is to reflect a subset of the FHIR constraints in ShEx.

**Comment by hsolbrig** [comment]
CIMI review of StructureDefinition showed some gaps in extensions and constraints.  Pester Stan

**Comment by dbooth-boston** [comment]
harold: We should see how many of the gaps in extensions and constraints can be covered with shex.

**Comment by hsolbrig** [comment]
This is definitely a shex issue.  Closed
