### ISSUE TITLE
What should be the media type for FHIR RDF in Turtle or other serializations?

### ISSUE THREAD

**Issue by dbooth-boston** [w3c/hcls-fhir-rdf#4]
ACTION: DBooth to ask EricP about media types for RDF that is FHIR [recorded in http://www.w3.org/2015/12/15-hcls-minutes.html#action01]

**Comment by mvdzel** [comment]
In the fhir-net-api ref impl I use "application/turtle+fhir" and "text/turtle", following the pattern that was already in there for json "application/json+fhir" and xml "application/xml+fhir".

**Comment by dbooth-boston** [comment]
David: The correct media types for turtle and json-ld are: text/turtle or application/ld+json

Harold: At the moment, FHIR examples are served as application/octet-stream.   Need to change that to text/turtle or application/ld+json.

ACTION: Harold to get the FHIR server updated to server the correct media type.

ACTION: David to ask Michael to update fhir-net-api to serve the correct media type (text/turtle or application/ld+json)

**Comment by ericprud** [comment]
This may be more of a FHIR issue, but the [`+xml` media types](https://tools.ietf.org/html/rfc7303) are defined to have the `xml` to the right of the `+` with the notion that you can trim off the stuff to the left and just use a generic `application/xml` handler.

**Comment by dbooth-boston** [comment]
Done.  The turtle and shex specs already say the correct media types to use.

ACTION: David to add media types for text/turtle and text/shex to module page

**Comment by dbooth-boston** [comment]
David: I emailed Michael today asking about correcting the media types in his implementation.
