### ISSUE TITLE
Updating Shex generator to handle required codings and codedelements

### ISSUE THREAD

**Issue by dbooth-boston** [w3c/hcls-fhir-rdf#40]

**Comment by dbooth-boston** [comment]
http://www.w3.org/2017/02/07-hcls-irc#T16-56-55

harold: Shex generation assumes that all values are type code, but there are several that are type coding or codedelement.
<dbooth> ... Need to fix that in the shex generator.
<dbooth> ... There are about 12 failing test now, because of that.

**Comment by hsolbrig** [comment]
This is a prerequisite for being able to add RDF links on other parts of the document

**Comment by dbooth-boston** [comment]
@ericprud Is this issue still relevant?  I'm trying to clean up the issues list.

**Comment by ericprud** [comment]
I suspect so, but it was @hsolbrig who discussed it in the IRC log. Harold?

**Comment by dbooth-boston** [comment]
Done
