### ISSUE TITLE
Harmonizing pre-coordinated and compositional terms in the information model

### ISSUE THREAD

**Issue by dbooth-boston** [w3c/hcls-fhir-rdf#50]
Discussed at:
http://www.w3.org/2017/04/11-hcls-irc#T15-47-38

**Comment by dbooth-boston** [comment]
More discussion at:
https://www.w3.org/2017/05/02-hcls-minutes.html#item02

**Comment by hsolbrig** [comment]
Significant enhancement but quite important

**Comment by dbooth-boston** [comment]
Should we close this as out of scope (of what we can address at present)?

**Comment by dbooth-boston** [comment]
Addressed by concept IRIs in R5
