### ISSUE TITLE
SNOMED Expressions in FHIR RDF

### ISSUE THREAD

**Issue by dbooth-boston** [w3c/hcls-fhir-rdf#51]
Discussion on zulip: https://chat.fhir.org/#narrow/stream/ontology/subject/SNOMED.20Expressions

Turtle example: http://build.fhir.org/observation-example-bmd.ttl.html

Same example in JSON: http://build.fhir.org/observation-example-bmd.json.html

Discussion on teleconference: https://www.w3.org/2017/06/13-hcls-minutes.html#item03

Harold: Suggest revisiting this in a month or two.  Michael Lawley and Linda Bird may help us.

**Comment by hsolbrig** [comment]
See #50

**Comment by dbooth-boston** [comment]
I think this issue should be consolidated with #50 .

**Comment by dbooth-boston** [comment]
Addressed by concept IRIs in R5

**Comment by tmprd** [comment]
Individual instances of post-coordinated codes can be represented with OWL anonymous classes (even added to CodeableConcepts). I haven't seen these used much, but it's perfectly valid:
```turtle
<http://hl7.org/fhir/Observation/bmd> a fhir:Observation ;
  fhir:bodySite [
    a [
        a owl:Class ;
        # Manchester syntax: ( sct:71341001  and (sct:272741003 some sct:7771000) )
        # With annotations loaded: ( "Bone structure of femur" and ("Laterality" some "Left") )
        owl:intersectionOf (
          sct:71341001 # Bone structure of femur
          [ 
            a owl:Restriction ;
            owl:onProperty sct:272741003 ; # Laterality
            owl:someValuesFrom sct:7771000 # Left
          ] 
      ) 
    ] ;
    # ^^^^^^^
    fhir:coding ( [
      fhir:system [
        fhir:v "http://snomed.info/sct"^^xsd:anyURI ;
        fhir:l <http://snomed.info/sct>
      ] ;
      fhir:code [ fhir:v "71341001:272741003=7771000" ]
    ] ) ; # example of a post coordinated term
    fhir:text [ fhir:v "Left Femur" ]
  ] . # 
```
This is proven to work: if you define an equivalent class with that criteria, then a reasoner will infer that the particular bodySite is an instance of the class.
```turtle
:LeftFemur rdf:type owl:Class ;
   owl:equivalentClass [ 
       owl:intersectionOf (
          sct:71341001 # Bone structure of femur
          [ 
            a owl:Restriction ;
            owl:onProperty sct:272741003 ; # Laterality
            owl:someValuesFrom sct:7771000 # Left
          ] 
       ) 
     a owl:Class
   ] .
```

```turtle
# Easier to see when not using a blank node:
<http://hl7.org/fhir/Observation/bmd> a fhir:Observation ;
  fhir:bodySite :myBodySite . 

# Name given to blank node
:myBodySite a fhir:CodeableConcept ;
    # rdf:type fhir:CodeableConcept ;
    a [
      a owl:Class ;
      owl:intersectionOf (
        sct:71341001 # Bone structure of femur
        [ 
          a owl:Restriction ;
          owl:onProperty :272741003 ; # Laterality
          owl:someValuesFrom :7771000
         ] # Left
      ) 
    ] ;
    fhir:coding ( [
      fhir:system [
        fhir:v "http://snomed.info/sct"^^xsd:anyURI ;
        fhir:l <http://snomed.info/sct>
      ] ;
      fhir:code [ fhir:v "71341001:272741003=7771000" ]
    ] ) ; # example of a post coordinated term
    fhir:text [ fhir:v "Left Femur" ] .

# Entails => :bodySite rdf:type :LeftFemur .
```

**Comment by tmprd** [comment]
I think we should note that concept IRIs for post-coordinated codes can be faithfully represented using an anonymous OWL class, but this requires a correct (or canonical) translation of the SNOMED expression to OWL. 
Unfortunately there isn't a nice way to encode this in the RDF Concept IRI Extension, since the whole point is that the post-coordinated code is an expression, not a name for something (like an IRI is).

**Comment by dbooth-boston** [comment]
Is there an automated translator available, to go from SNOMED post-coordinated expressions to OWL?  If so, then I think it would be very good to mention it in the rdf.html page.

Also, is it now clear what IRI stem should be used with SNOMED expressions, such that the expression is encoded in a single concept IRI?  If so, then I think that would also be good to mention.  That would allow the concept IRI (containing a SNOMED expressions as a "code") to be used with RDF Concept IRI Extension, though the user wanting to convert that concept IRI to OWL would have to recognize the IRI stem and apply the SNOMED-expression-to-OWL translator to the encoded expression.

**Comment by tmprd** [comment]
> Is there an automated translator available, to go from SNOMED post-coordinated expressions to OWL? If so, then I think it would be very good to mention it in the rdf.html page.

### Option 1: Add link to SNOMED converter
Technically I think there is somewhere in here: https://github.com/IHTSDO/snomed-owl-toolkit

### Option 2: Just summarize guidance 
But I'm wary of adding more external links to the rdf.html page. I would prefer to update what it says now, framed in terms of what applications can do, not in terms of what to expect in the serialization:
```diff
- *As of this writing (5-Sep-2022) it is not clear what IRI stem is most appropriate 
- when writing a SNOMED CT post-coordinated code expression.
+ SNOMED CT post-coordinated expressions have canonical translations into axioms used in anonymous OWL classes. 
+ FHIR RDF Turtle applications may represent these codes with anonymous class assertions, instead of a concept IRI, 
+ if the appropriate for the SNOMED concept and FHIR data element. 
```

### Option 3: IRI for anonymous class?
> Also, is it now clear what IRI stem should be used with SNOMED expressions, such that the expression is encoded in a single concept IRI? If so, then I think that would also be good to mention. 

The equivalent RDF representation is an anonymous node, so I don't think it should be expressed with an IRI.

> That would allow the concept IRI (containing a SNOMED expressions as a "code") to be used with RDF Concept IRI Extension, though the user wanting to convert that concept IRI to OWL would have to recognize the IRI stem and apply the SNOMED-expression-to-OWL translator to the encoded expression.

I don't think encoding the same expression into the concept IRI is useful, and that IRI would not canonically represent the concept in the OWL ontology. 
Example: `71341001:272741003=7771000` converted to concept IRI http://snomed.info/id/71341001%3A272741003%3D7771000
That doesn't add anything helpful.

There is a concept equivalent to this with a name already: [Structure of bone of left femur (body structure)](https://www.ebi.ac.uk/ols4/ontologies/snomed/classes/http%253A%252F%252Fsnomed.info%252Fid%252F722738000)
using the concept IRI http://snomed.info/id/722738000 
But replacing the post-coordinated expression with that IRI is something that should be done carefully. I guess a more complex algorithm could re-classify instances of the post-coordinated code with its named equivalent. That could actually be very useful. 
But this is all going way beyond what should be in the FHIR core standard for serialization. Better to detail that in an IG #242 or a paper + example repo.
