### ISSUE TITLE
FHIR Ontology (fhir.ttl) naming convention clash

### ISSUE THREAD

**Issue by hsolbrig** [w3c/hcls-fhir-rdf#53]
There are several classes in the FHIR ontology (fhir.ttl) that have ambiguous names.  As an example, `DiagnosisComponent` is the target of `Encounter.diagnosis`, `EpisodeOfCare.diagnosis`, `Claim.diagnosis` and `ExplanationOfBenefit.diagnosis`.   (Despite some seeming similarity), all four of these reference different types.  `DiagnosisComponent` ends up being the aggregate (intersection) of all of the target types.

Recommendation: the fhir.ttl generator should prefix the type onto the component name - we should have `EncounterDiagnosisComponent`, `EpisodeOfCareDiagnosisComponent`, etc.

Note: None of these names appear in the actual RDF -- this change will have no impact on the FHIR RDF specification itself

**Comment by hsolbrig** [comment]
Changes have been proposed  -- instead of "DiagnosisComponent", code now exists to generate "EncounterDiagnosos", "ClaimDiagnosis", "ExplanationOfBenefitDiagnosis", etc.  Have filed an issue with FHIR http://gforge.hl7.org/gf/project/fhir/tracker/?action=TrackerItemEdit&tracker_item_id=13594&start=0 and am awaiting the outcome of a discussion on https://chat.fhir.org/#narrow/stream/ontology/subject/Hosting  .  Will commit changes if approved.

**Comment by dbooth-boston** [comment]
Grahame approved the change: https://chat.fhir.org/#narrow/stream/ontology/subject/Hosting
