### ISSUE TITLE
HAPI FHIR server needs to support Turtle

### ISSUE THREAD

**Issue by dbooth-boston** [w3c/hcls-fhir-rdf#55]
It is the most commonly used FHIR server, but it does not yet support Turtle.
http://hapifhir.io/
https://github.com/jamesagnew/hapi-fhir/

**Comment by tian000** [comment]
+1

**Comment by dbooth-boston** [comment]
Done!   Not sure of the best URI for info, but here's something: https://hapifhir.io/hapi-fhir//apidocs/hapi-fhir-structures-dstu3/org/hl7/fhir/dstu3/utils/formats/Turtle.LineOutputStreamWriter.html

**Comment by dbooth-boston** [comment]
https://github.com/hapifhir/hapi-fhir/blob/master/hapi-fhir-structures-r4/src/test/java/ca/uhn/fhir/parser/RDFParserTest.java

**Comment by ericprud** [comment]
> Done! Not sure of the best URI for info, but here's something: https://hapifhir.io/hapi-fhir//apidocs/hapi-fhir-structures-dstu3/org/hl7/fhir/dstu3/utils/formats/Turtle.LineOutputStreamWriter.html

That is a legacy DSTU3 Turtle writer. If someone wants to use RDF with DSTU3, I believe the best thing would be to use  [`FhirContext.newRDFParser`](https://github.com/hapifhir/hapi-fhir/blob/4bb495e9d717c64e611ab0f93483c44b8445d33e/hapi-fhir-base/src/main/java/ca/uhn/fhir/context/FhirContext.java#L808), which (as for JSON and XML), both parses:
``` java
IBaseResource resource = ctx.newRDFParser().parseResource(inputStream);
```
and serializes:
``` java
String turtle = ctx.newRDFParser().encodeResourceToString(resource);
```
This parser [`ca.uhn.fhir.parser.RDFParser`](https://github.com/hapifhir/hapi-fhir/blob/master/hapi-fhir-base/src/main/java/ca/uhn/fhir/parser/RDFParser.java) has been tested with all [`R4`](https://github.com/hapifhir/hapi-fhir/blob/master/hapi-fhir-structures-r4/src/test/java/ca/uhn/fhir/parser/RDFParserTest.java) and [`R5`](https://github.com/hapifhir/hapi-fhir/blob/master/hapi-fhir-structures-r5/src/test/java/ca/uhn/fhir/parser/RDFParserTest.java) examples.
