### ISSUE TITLE
Where to publish code ontologies

### ISSUE THREAD

**Issue by dbooth-boston** [w3c/hcls-fhir-rdf#56]
Initially raised at https://www.w3.org/2017/07/11-hcls-minutes.html#item02
harold: "Need to decide whether to publish [the FHIR code ontologies] on the FHIR site or put it in a terminology service. Need to discuss that with Rob Hausam."

**Comment by hsolbrig** [comment]
Decision was to do it on the FHIR stuff

**Comment by dbooth-boston** [comment]
Closing this, because we've answered the question of where we want to publish the code ontologies (i.e., on the FHIR site along with the rest of the FHIR spec).  Now it just has to be implemented.  ;)
