### ISSUE TITLE
FHIR code ontology file extensions -- .owl vs .ttl

### ISSUE THREAD

**Issue by dbooth-boston** [w3c/hcls-fhir-rdf#59]
Which extension should be used, .owl or .ttl?  They are turtle files containing OWL.

Originally raised at https://www.w3.org/2017/07/11-hcls-minutes.html#item02
[[
harold: [ . . . ] I've been using a .owl suffix. We've been using .ttl for other things.
]]

**Comment by dbooth-boston** [comment]
Maybe this should be merged with issue #48 ?

**Comment by hsolbrig** [comment]
Still needs discussion - "-owl.ttl" vs. ".owl"

**Comment by dbooth-boston** [comment]
What we did is what we did.  ttl?
