### ISSUE TITLE
Downloadable FHIR ontology - Who maintains it and how?

### ISSUE THREAD

**Issue by dbooth-boston** [w3c/hcls-fhir-rdf#6]
Our list of deliverables includes:
http://wiki.hl7.org/index.php?title=RDF_for_Semantic_Interoperability#Deliverables_and_Editors

> 1. Downloadable FHIR ontology (generated by the FHIR spec build process?)

Grahame comments:

> > ```
> > A key question is who maintains this, and how. If it's in the
> > build process, it will be maintained and robust because we will be
> > forced to update it as the conformance artifacts it depends on
> > change. if it's outside the build, we'll need to maintain various
> > versions of it, and it will be broken unless one of us keeps it up
> > to date. 
> > ```

**Comment by twamarc** [comment]
Ideally this should be maintained in the build process (or at least in closest way to the build process).
Otherwise we will need to maintain the same thing in different places and this is tricky.

**Comment by dbooth-boston** [comment]
Resolved.  See: http://www.w3.org/2017/02/07-hcls-irc#T17-02-11
