### ISSUE TITLE
FHIR build needs RDF QA check (roundtrip?)

### ISSUE THREAD

**Issue by dbooth-boston** [w3c/hcls-fhir-rdf#63]
FHIR build needs RDF QA check (roundtrip?).  FHIR build was generating bad RDF (though now fixed)

https://www.w3.org/2018/03/27-hcls-irc#T15-10-24

**Comment by hsolbrig** [comment]
Double - check, I think it is in there

**Comment by dbooth-boston** [comment]
Probably good enough now in R5
