### ISSUE TITLE
Examples page doesn't have RDF

### ISSUE THREAD

**Issue by hsolbrig** [w3c/hcls-fhir-rdf#64]
FHIR Examples (e.g. http://build.fhir.org/medicationexample0301.html) have links to XML and JSON but not RDF.  If you insert the RDF link, the build fails because value sets and other resources aren't converted to RDF

**Comment by dbooth-boston** [comment]
I spoke to Grahame about it several weeks ago, and it seems to be fixed now, so I'm closing this issue.
