### ISSUE TITLE
FHIR extensions

### ISSUE THREAD

**Issue by ericprud** [w3c/hcls-fhir-rdf#67]
A selling point of RDF is that it has extensibility built into any novel predicate. Extensions can be modeled by:

1.  blindly applying the StructureDefinition -> ShEx algorithm.
2. using the extension's URL as a predicate and the extension's value as the object.

**Comment by dbooth-boston** [comment]
I think it's too late to consider this change for the Aug 21, 2022 R5 deadline, but we could consider discussing it later.

**Comment by ericprud** [comment]
I wonder if this issue should have some tag that we remember to look for in the closed issues when we get past R5.

**Comment by dbooth-boston** [comment]
Done in R5
