### ISSUE TITLE
How to represent FHIR extensions in RDF?

### ISSUE THREAD

**Issue by ericprud** [w3c/hcls-fhir-rdf#68]
A selling point of RDF is that it has extensibility built into any novel predicate. Extensions can be modeled by:
1  blindly applying the StructureDefinition -> ShEx algorithm.
2. using the extension's URL as a predicate and the extension's value as the object.
It's also possible to define isomorphisms between the two.

**Comment by dbooth-boston** [comment]
Duplicate of #67
