### ISSUE TITLE
Modify the FHIR spec build process to produce RDF artifacts -- Who and how?

### ISSUE THREAD

**Issue by dbooth-boston** [w3c/hcls-fhir-rdf#7]
Draft spec: http://w3c.github.io/hcls-fhir-rdf/spec/

One of our deliverables:
http://wiki.hl7.org/index.php?title=RDF_for_Semantic_Interoperability#Deliverables_and_Editors

> 1. Modify the FHIR spec build process, so when it produces JSON versions of everything and tests roundtripping, it also produces RDF versions of everything and tests roundtripping for RDF.

David comments:

> > ```
> >      - Michael will use Eric's ShEx in doing #5 (Modify the FHIR
> >     spec build process), so that the build process will generate
> >     RDF versions of all of the examples on the individual resource
> >     pages, alongside of the XML and JSON versions.
> > ```

Grahame comments:

> > ```
> > I would rather see this done by the reference implementation as
> > the JSON conversion is done now.
> > ```

**Comment by mvdzel** [comment]
Right now each of the resource pages contains some form of template. It are not templates in any official format. ShEx is an official form of RDF templates. Right so far?
The current build proces is java based, the ShEx is not. So the only clean way to include this is to rewrite the ShEx generation in java or xslt and call it from the build tool.

**Comment by ericprud** [comment]
ShEx is language agnostic. There is a [java/scala implementation](http://labra.github.io/ShExcala/) but I think what you really want in java is something which parses structural definitions and emits ShEx. At present, [that code](https://github.com/w3c/hcls-fhir-rdf/blob/gh-pages/scripts/generate_shex) is all written in python, but it should be easy to javify.

**Comment by dbooth-boston** [comment]
Grahame and others have already implemented this in the build process, so I am closing this.

**Comment by ericprud** [comment]
On Feb 17, 2016 9:25 AM, "Michael van der Zel" notifications@github.com
wrote:

> Right now each of the resource pages contains some form of template. It
> are not templates in any official format. ShEx is an official form of RDF
> templates. Right so far?
> The current build proces is java based, the ShEx is not. So the only
> clean way to include this is to rewrite the ShEx generation in java or xslt
> and call it from the build tool.

My implementation of ShEx is in JavaScript (and a very old one in C++) but
there's another in Scala which is about a month or if date wrt the
ShExpressivity that we require. I expect the maintainer to resurface after
August vacations.

**Comment by ericprud** [comment]
On Aug 19, 2016 9:05 PM, "Eric Prud'hommeaux" eric@w3.org wrote:

> On Feb 17, 2016 9:25 AM, "Michael van der Zel" notifications@github.com
> wrote:
> 
> > Right now each of the resource pages contains some form of template. It
> > are not templates in any official format. ShEx is an official form of RDF
> > templates. Right so far?
> > The current build proces is java based, the ShEx is not. So the only
> > clean way to include this is to rewrite the ShEx generation in java or xslt
> > and call it from the build tool.
> 
> My implementation of ShEx is in JavaScript (and a very old one in C++)
> but there's another in Scala which is about a month or if date wrt the
> ShExpressivity that we require. I expect the maintainer to resurface after
> August vacations.

Oh, and someone at Lille2 is working on a pure Java implementation.
