### ISSUE TITLE
Primitive data types use "_" prefix in JSON

### ISSUE THREAD

**Issue by hsolbrig** [w3c/hcls-fhir-rdf#71]
For primitive types, _ is added before the field key in the JSON.  It would (probably?) be impractical to generate both `attr` and `_attr` for every primitive FHIR attribute, so some sort of preprocessing will be needed to address this issue.

For example:

[plandefinition-example-kdn5-simplified.json](http://build.fhir.org/plandefinition-example-kdn5-simplified.json):  see _relatedArtifact[1].type_

[EXTENSION]: http://example.com/UNKNOWN#_type [object Object]

**Comment by dbooth-boston** [comment]
Done in R5.  Handled by not hoisting.
