### ISSUE TITLE
Outdated ShEx (?)

### ISSUE THREAD

**Issue by hsolbrig** [w3c/hcls-fhir-rdf#73]
We are getting the following conversion errors:

Files:

    medicationrequestexample1.json
    medicationrequestexample2.json
    medicationrequestxxxx.json

Path:

    MedicationRequest.reason
    MedicationRequest.concept
    …

File:

    medicinalproductdefinition-example.json

Path:

    MedicinalProductDefinition.manufacturingBusinessOperation.authorization

**Comment by dbooth-boston** [comment]
Should be fixed.  Shex is autogenerated in the build.
