### ISSUE TITLE
Simplifying primitive properties while still supporting FHIR extensions, aka hoisting scalars

### ISSUE THREAD

**Issue by dbooth-boston** [w3c/hcls-fhir-rdf#77]
The problem is that when we designed FHIR RDF R4 (the initial version of FHIR RDF), we introduced an extra blank node and fhir:value property on primitive properties.  For example, fhir:gender is represented like this:
```
fhir:Patient.gender [ fhir:value "male" ] .
```

instead of simply being:
```
fhir:Patient.gender "male" .
```

We designed it this way intentionally, because FHIR allows _any_ property to be extended, so the extra blank node provides a place to attach the extension (if needed).  (See example below.)  However, in the years since that design, after accumulating some practical experience using FHIR RDF, it has become clear that the extra blank node and fhir:value property makes it significantly more difficult to access and query those simple properties, which usually are not extended anyway.  In other words, we made _every_ use of a primitive property more difficult, just to accommodate the rare case in which someone wants to add a FHIR extension to it.  This violates the general design guidance of making the common use cases easy, and the rare use cases possible.  Hence, the point of this issue is to reconsider this design choice, to see if we can make the common use case easy -- without requiring the extra blank node and property -- while still somehow enabling the property to have a FHIR extension if needed.

_[Sub-issue: How should modifying extensions be represented?  NOTE: Discussion of modifier extensions has now been moved to issue #93 .]_

**Option 0: Do nothing.  Keep the R4 approach of everything being an object property**

JSON example of non-modifying extension, from R4:

```
...
"gender": "male",
  "birthDate": "1974-12-25",
  "_birthDate": {
    "extension": [
      {
        "url": "http://hl7.org/fhir/StructureDefinition/patient-birthTime",
        "valueDateTime": "1974-12-25T14:35:45-05:00"
      }
    ]
  },
```

Turtle equivalent in R4:

```
...
fhir:Patient.gender [ fhir:value "male" ] ;
fhir:Patient.birthDate [
     fhir:value "1974-12-25"^^xsd:date;
     fhir:Element.extension [
       fhir:index 0;
       fhir:Extension.url [ fhir:value "http://hl7.org/fhir/StructureDefinition/patient-birthTime" ];
       fhir:Extension.valueDateTime [ fhir:value "1974-12-25T14:35:45-05:00"^^xsd:dateTime ]
     ]
  ];
```

**Comment by gaurav** [comment]
I like extension option 2, suboption "Primitive example converted to R5 JSON-LD". However, I think the Turtle example is <s>slightly wrong, since I don't think you can include dictionary-type structures directly in Turtle</s> confusing, because then we can't set a domain on the `fhir:Patient.birthDate` property, which could be either an extension or a patient. I think this would work better:

**REJECTED: Option 2b: Sibling extension property connected by fhir:extensionPath:**

_NOTE: This option was [eliminated on 9/9/21](https://www.w3.org/2021/09/09-hcls-minutes.html)_

```turtle
<http://build.fhir.org/Patient/example>
  fhir:nodeRole           "fhir:treeRoot" ;
  fhir:Resource.id        "example" ;
  fhir:Patient.birthDate  "1974-12-25" ;
  fhir:extension 
    [ 
      fhir:extensionPath fhir:Patient.birthDate ;
      fhir:index 0 ; # Ordering mechanism TBD
      fhir:Extension.url <http://hl7.org/fhir/StructureDefinition/patient-birthTime> ;
      fhir:Extension.valueDateTime "1974-12-25T14:35:45-05:00"
    ]
```

_Note: I (@dbooth-boston ) took the liberty of slightly editing this to remove the unneeded outer list around the extension, since the fhir:index property is intended to retain the ordering of multiple extensions._

Pros: 
- No need to FILTER out extensions when querying for primitive property value.
- No need to use ontology relationship to connect `foo` to `_foo`.

Cons:
- Slightly weird that you have to access `extension/foo` instead of `foo/extension`.
- The fhir:index applies to all (sibling) extensions -- not only fhir:Patient.birthDate extensions -- so it may be more difficult to turn this back into a list of fhir:Patient.birthDate extensions if desired.

**Comment by dbooth-boston** [comment]
**REJECTED Extension option 4a: Have both a primary object property and a short-cut datatype property** 

_Note: This option was [eliminated on 9/16/21](https://www.w3.org/2021/09/16-hcls-minutes.html)._

This is conceptually similar to option 3, in that it uses two properties, though the naming convention differs and the object would include the entire R4 object instead of only holding the extension:

```
fhir:Patient.birthDateValue "1974-12-25"^^xsd:date ;
fhir:Patient.birthDate [
     fhir:value "1974-12-25"^^xsd:date;
     fhir:Element.extension [
       fhir:index 0;
       fhir:Extension.url [ fhir:value "http://hl7.org/fhir/StructureDefinition/patient-birthTime" ];
       fhir:Extension.valueDateTime [ fhir:value "1974-12-25T14:35:45-05:00"^^xsd:dateTime ]
     ]
  ];

. . .
# Ontology relationship:
fhir:Patient.birthDateValue fhir:extensionProperty fhir:Patient.birthDate .
```

Pros:
- Backward compatible with R4 RDF

Cons:
- Redundant data in fhir:Patient.birthDateValue and fhir:value
- The fhir:Patient.birthDate property is an extension, instead of the original property, which does not align with the JSON or XML and may be confusing

**REJECTED: Extension option 4b: Have both a primary datatype property and an adjunct object property**

_Note: This option was [eliminated on 9/16/21](https://www.w3.org/2021/09/16-hcls-minutes.html)._

Similar to option 4a, but reversing the naming convention:

```
fhir:Patient.birthDate "1974-12-25"^^xsd:date ;
fhir:Patient.birthDateExtension [
     fhir:value "1974-12-25"^^xsd:date;
     fhir:Element.extension [
       fhir:index 0;
       fhir:Extension.url [ fhir:value "http://hl7.org/fhir/StructureDefinition/patient-birthTime" ];
       fhir:Extension.valueDateTime [ fhir:value "1974-12-25T14:35:45-05:00"^^xsd:dateTime ]
     ]
  ];

. . .
# Ontology relationship:
fhir:Patient.birthDate fhir:extensionProperty fhir:Patient.birthDateExtension .
```

Pros:
- Aligns with JSON and XML, in that the fhir:Patient.birthDate property directly holds the value.

Cons:
- Redundant data in fhir:Patient.birthDateValue and fhir:value
- Not backward-compatible with R4, though the fhir:Patient.birthDateExtension property has the same structure as in R4.

**Comment by ericprud** [comment]
### Option 5a: Use extension name as predicate

``` turtle
fhir:Patient.birthDate [
    fhir:value "1974-12-25"^^xsd:date ;
    <http://hl7.org/fhir/StructureDefinition/patient-birthTime> [
        fhir:index 0;
        fhir:Extension.valueDateTime "1974-12-25T14:35:45-05:00"^^xsd:dateTime
    ] ;

# Ontology:
<http://hl7.org/fhir/StructureDefinition/patient-birthTime> a fhir:ExtensionProperty .
# Extension ontology:
fhir:Patient.birthDate fhir:extensionProperty <http://hl7.org/fhir/StructureDefinition/patient-birthTime> .
```

Pros:

- Uses RDF-friendly URL as the predicate

Cons:
- Doesn't make birthDate value easier to access -- still have the extra blank node on primitive datatypes.

**Comment by dbooth-boston** [comment]
Copied this checklist item from the preprocessing checklist issue: Connect FHIR extension element "_foo" to element "foo", so that an RDF query can traverse from any element ?foo to its extensions, without hard-coding the element names. See slide 8: https://lists.w3.org/Archives/Public/www-archive/2019Nov/att-0000/FHIRRdf.pdf

**Comment by dbooth-boston** [comment]
The issue of connecting FHIR extension element "_foo" to element "foo" does not necessarily have to be addressed in the preprocessor, because it is a static relationship -- it does not depend on the instance data -- so it could be included in the ontology instead of being generated in the instance data.

**Comment by ericprud** [comment]
While hoisted scalars are wayyy nicer to query or access via graph API, hoisting conflicts with the fact that OWL (DL?) forces a choice between ObjectProperties and DatatypeProperties. This arises with e.g. rd**H fhir:code:
``` turtle
  fhir:code [
    fhir:coding (
      [
        a <http://loinc.org/rdf#15074-8>;
        fhir:system "http://loinc.org"^^xsd:anyURI;
        fhir:code "15074-8";
        fhir:display "Glucose [Moles/volume] in Blood"
      ]
    )
  ];
```
where fhir:code appears to be both an ObjectProperty:
``` turtle
<Obvservation> rdfs:subClassOf [owl:obProperty fhir:code ; owl:allValuesFrom <CodeableConcept>].
```
and a DatatypeProperty:
``` turtle
<Coding> rdfs:subClassOf [owl:obProperty fhir:code ; owl:allValuesFrom xsd:string].
```

Another example is rdv*H fhir:value: 
``` turtle
  fhir:value [
    a fhir:Quantity;
    fhir:value 6.3;
    fhir:system "http://unitsofmeasure.org"^^xsd:anyURI;
    fhir:code "mmol/L"
  ];
```
with [fhir:value](https://build.fhir.org/observation#a14.) an ObjectProperty:
``` turtle
<Observation> rdfs:subClassOf [
  owl:onProperty fhir:value ;
  owl:allValuesFrom [owl:unionOf (<Quantity>, <CodeableConcept>, <string> …) ] ] .
```
and a DatatypeProperty:
``` turtle
<Quantity> rdfs:subClassOf [owl:onProperty fhir:value; owl:allValuesFrom xsd:decimal].
```

**Comment by dbooth-boston** [comment]
In resolving #102, we also resolved this issue: AGREED: option 5 [of issue 102], not hoist scalars (same as R4)

https://www.w3.org/2022/07/28-hcls-minutes.html#t01
