### ISSUE TITLE
Context sensitive date data types

### ISSUE THREAD

**Issue by hsolbrig** [w3c/hcls-fhir-rdf#78]
The FHIR [date]( http://build.fhir.org/datatypes.html#date) and [dateTime](http://build.fhir.org/datatypes.html#dateTime) data types can map to one of `xsd:date`, 'xsd:dateTime`, `xsd:gYear` or `xsd:gYearMonth` depending on the actual value.  

This seems like possible overkill from the RDF, especially when one considers the fact that only `xsd:dateTime` is recognized by most OWL processors (see: https://www.w3.org/TR/2012/REC-owl2-syntax-20121211/#IRIs)

Would propose that the RDF specification unconditionally map  `fhir:date` and `fhir:dateTime` types to `xsd:dateTime`

**Comment by dbooth-boston** [comment]
See also #62: xsd:date, xsd:time etc. do not work with OWL.

**Comment by gaurav** [comment]
I think we should just embrace the [Seven Property Model](https://www.w3.org/TR/xmlschema11-2/#theSevenPropertyModel) and tell people to use the right type given how precise their date is. Yes, this will cause problems with OWL and with other systems that don't implement this properly, but they're wrong and should do better.

One terrible way of resolving this would be to require that values in xsd:dateTime are always required, and then additional, less precise options (such as xsd:gYearMonth) can be additionally provided, with any compliant implementation required to use the lease precise option provided. But that seems like it's just asking for trouble :)

**Comment by ericprud** [comment]
> I think we should just embrace the [Seven Property Model](https://www.w3.org/TR/xmlschema11-2/#theSevenPropertyModel) and tell people to use the right type given how precise their date is. Yes, this will cause problems with OWL and with other systems that don't implement this properly, but they're wrong and should do better.

I read this as supporting specifically-typed literals in FHIR/RDF. (I also support that.) The cost is that conversions have to inspect the scalar value to do the conversion. For instance, a single JSON-LD @context won't do these conversions:

``` JSON
"2021" -> "2021"^^xsd:gYear
"2021-10" -> "2021-10"^^xsd:gYearMonth
"2021-10-01" -> "2021-10-01"^^xsd:date
"2021-10-01T18:21:17+02:00" -> "2021-10-01T18:21:17+02:00"^^xsd:dateTime
```

If you have special knowledge of a particular data source, you might know that e.g. all of the Observations effectiveTiming/events are xsd:dateTimes, which might allow you to do some blanket casting with having to parse every value.


> One terrible way of resolving this would be to require that values in xsd:dateTime are always required, and then additional, less precise options (such as xsd:gYearMonth) can be additionally provided, with any compliant implementation required to use the lease precise option provided. But that seems like it's just asking for trouble :)

agreed. RDF already does a perfectly good job of capturing this data. It's just that we have to pay attention when importing.

**Comment by gaurav** [comment]
I haven't gotten FHIRJsonLDAmiaPaper repository to work yet, but it does include code for preprocessing FHIR JSON files to add the right type for partial dates:

https://github.com/fhircat/FHIRJsonLDAmiaPaper/blob/eac62b6a5030fd82223a28bade05c14e1762b577/fhir_jsonld_amia/json_preprocessor.py#L87-L110

So adding that to the structural transforms does appear to be a good way to do this.

**Comment by dbooth-boston** [comment]
From [minutes of 10/14/2021](https://www.w3.org/2021/10/14-hcls-minutes.html#t03):

```
AGREED: close 78 with no changes to R4.
```

**Comment by dbooth-boston** [comment]
See also comments in issue #86 about how to handle this in JSON-LD 1.1

**Comment by tmprd** [comment]
Just want to point out here that [11 examples](https://hl7.org/fhir/R5/subscriptionstatus-examples.html) of SubscriptionStatus (all except the "bare" one) use [xsd:datetime](https://www.w3.org/TR/xmlschema-2/#dateTime) with 7 [digits](https://www.w3.org/TR/xmlschema-2/#year-sec-conformance) of fractional seconds. The HermiT reasoner didn't support this until [v1.4.4](https://github.com/owlcs/hermit-reasoner/issues/5)
