### ISSUE TITLE
Add an explicit relationship between FHIR properties and their extensions

### ISSUE THREAD

**Issue by dbooth-boston** [w3c/hcls-fhir-rdf#84]
A FHIR JSON extension like this:

```
 "active": true,
 "_active": {
   "extension" : [ {
      "url" : "http://example.org/fhir/boolean/Certainty",
      "valueDecimal" : 0.75
   }]
 }
```

will come through as RDF like this:

```
[] fhir:active   true ;
   fhir:_active  [
     fhir:extension [
       fhir:index 0 ;       # To retain ordering of multiple extensions
       fhir:url  "http://example.org/fhir/boolean/Certainty" ;
         fhir:valueDecimal  0.75
     ]
   ] .
```

For RDF processing it would be helpful if an explicit relationship were expressed between fhir:active and fhir:_active triples, so that applications do not have to parse apart URIs looking for similar URIs that differ only by a preceding underscore in the last part.  It should be easy in SPARQL (for example) to look for any extensions to any properties.

Should our JSON pre-processor add such a relationship?  If so, what should it be?  One obvious possibility might be to declare:

```
fhir:active fhir:extensionProperty fhir:_active .
```

Using that, a SPARQL query to find all extensions on property ?p might be something like this:

```
SELECT ?node ?p ?pExtension WHERE {
  ?p fhir:extensionProperty ?pExtension .
  ?node ?p ?value ;
        ?pExtension ?extensionValue .
```

I don't know how efficient this will be to process though, because ?pExtension is a variable, which may require table scans instead of indexing.  In the past I have used nested SELECT statements to force variables to be bound, to help performance.  

```
SELECT ?node ?p ?pExtension WHERE {
  { SELECT ?p ?pExtension WHERE {
      ?p fhir:extensionProperty ?pExtension . }}
  ?node ?p ?value ;
        ?pExtension ?extensionValue .
```

(I have not tested this, so I am merely speculating.)

Is a better approach possible, for explicitly connecting fhir:active properties to their corresponding fhir:_active properties?

**Comment by dbooth-boston** [comment]
@balhoff or Daniel Stone, was this implemented in the generated OWL ontology?

**Comment by balhoff** [comment]
@dbooth-boston there are triples in the OWL ontology such as:

```turtle
fhir:sourceScope fhir:modifierExtensionProperty fhir:_sourceScope .
```

and

```turtle
fhir:Patient fhir:modifierExtensionClass fhir:_Patient .
```

**Comment by dbooth-boston** [comment]
Done.  It is in the ontology.  https://build.fhir.org/fhir.rdf.ttl.zip
