### ISSUE TITLE
Resolve ElementDefinition.type.aggregation 

### ISSUE THREAD

**Issue by hsolbrig** [w3c/hcls-fhir-rdf#91]
The existing RDF transformations do not handle this 100% correctly.  It was discovered and corrected for in the JSON-LD transformation code.  We need to:
* Summarize what the issue actually is (by looking at the Python or Java comparison code)
* Decide what we want to do with the existing specification as it exists today
* Decide how to (or whether) to update existing implementations.  

Derived from issue #32

**Comment by dbooth-boston** [comment]
No action needed.
