### ISSUE TITLE
Distinguish int, decimal and double numbers in FHIR JSON preprocessor

### ISSUE THREAD

**Issue by dbooth-boston** [w3c/hcls-fhir-rdf#99]
[JSON numbers](https://datatracker.ietf.org/doc/html/rfc8259#section-6) as literals are essentially a union of [xsd:int](https://www.w3.org/TR/xmlschema-2/#int), [xsd:decimal](https://www.w3.org/TR/xmlschema-2/#decimal) and [xsd:double](https://www.w3.org/TR/xmlschema-2/#double).

Should we make the preprocessor do a runtime check of each JSON number, to emit it as one of those three types, rather than defaulting to emitting them all as xsd:double?

**Comment by ericprud** [comment]
```
    if (nestScalar.type === "NodeConstraint") {
      typedValue = {
        "@type": nestScalar.datatype.replace(/^http:\/\/www\.w3\.org\/2001\/XMLSchema#/, "xsd:"),
        "@value": jsonValue,
      };
    } …
```
— https://github.com/fhircat/fhir-rdf-playground/blob/7b79da834bb6b86e40a25586ff019df8ec0fdde9/fhirlib/FhirPreprocessors.js#L290

**Comment by dbooth-boston** [comment]
Excellent.  I think this change is now ready for me to document.

**Comment by dbooth-boston** [comment]
Done in R5
